### ISSUE TITLE
Fix typo for 'airplane-variant'

### ISSUE THREAD

**Issue by matthewbirtch** [deanwhillier/mattermost#17]
@deanwhillier what's the best way to fix the typo for `airplane-variant` icon (right now it is `airplan-variant`). Just wanted to make sure this won't blow things up

**Comment by deanwhillier** [comment]
Looks like you can edit the file directly in Github and change the name without issue. You'd have to make a PR out of it of course, but otherwise its the same as adding a new icon. The config file is re-generated with each build, and the data is taken from the files themselves, so it should always match the state of the SVG folder. :)

I already updated the name while testing.

**Comment by matthewbirtch** [comment]
ok, sweet. Thanks!
